# Generated by Django 4.1.3 on 2022-12-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
